# Generated by Django 6.0.7 on 2026-07-27 18:54

import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_alter_role_options_alter_roleaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'فارسی')], default=iam.models.default_language, max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
