# Generated by Django 6.0.7 on 2026-07-22 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_tas', models.ManyToManyField(blank=True, related_name='courses_as_head_ta', to=settings.AUTH_USER_MODEL)),
                ('professors', models.ManyToManyField(blank=True, related_name='courses_as_professor', to=settings.AUTH_USER_MODEL)),
                ('tas', models.ManyToManyField(blank=True, related_name='courses_as_ta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
