# Generated by Django 6.0.7 on 2026-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-semester', 'code']},
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, default='', help_text='e.g. Fall 2026', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'semester')},
        ),
    ]
