# Generated by Django 6.0.7 on 2026-07-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_students_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('min_members', models.PositiveSmallIntegerField(default=1)),
                ('max_members', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='courses.course')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='courses.student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.grouptype')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddConstraint(
            model_name='grouptype',
            constraint=models.CheckConstraint(condition=models.Q(('min_members__lte', models.F('max_members'))), name='group_type_min_lte_max'),
        ),
        migrations.AlterUniqueTogether(
            name='grouptype',
            unique_together={('course', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('type', 'number')},
        ),
    ]
