# Generated by Django 6.0.7 on 2026-07-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_grouptype_group_grouptype_group_type_min_lte_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='signup_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
