# Generated by Django 6.0.7 on 2026-07-26 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_grouptype_signup_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('signup_token', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_items', to='courses.course')),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_items', to='courses.grouptype')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='HandoffSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('teammates_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_bookings', to='courses.student')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_slots', to='courses.group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courses.handoffitem')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='handoff_slot_ends_after_start'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('item', 'group'), name='handoff_one_slot_per_group')],
            },
        ),
    ]
