# Generated by Django 6.0.7 on 2026-07-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_handoffitem_handoffslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffitem',
            name='hide_ta',
            field=models.BooleanField(default=True),
        ),
    ]
