# Generated by Django 6.0.7 on 2026-07-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_handoffitem_hide_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffitem',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='handoffitem',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
