# Generated by Django 6.0.7 on 2026-07-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_handoffitem_break_minutes_handoffitem_slot_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
