# Generated by Django 6.0.7 on 2026-07-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_gradingsheet_subgrade_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
