# Generated by Django 6.0.7 on 2026-07-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_students_student'),
        ('grading', '0003_score_comment'),
    ]

    operations = [
        # Scores used to point at user accounts; those ids mean nothing as
        # Student rows, so the old rows go rather than dangle.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("grading", "Score").objects.all().delete(),
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.student'),
        ),
    ]
