# Generated by Django 6.0.7 on 2026-07-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_alter_score_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheet',
            name='public_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
