# Generated by Django 6.0.7 on 2026-07-26 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_gradingsheet_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradingtask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradingtask',
            name='subgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='grading.subgrade'),
        ),
        migrations.AddConstraint(
            model_name='gradingtask',
            constraint=models.UniqueConstraint(condition=models.Q(('subgrade__isnull', True)), fields=('component', 'assigned_to'), name='one_component_task_per_grader'),
        ),
        migrations.AddConstraint(
            model_name='gradingtask',
            constraint=models.UniqueConstraint(condition=models.Q(('subgrade__isnull', False)), fields=('subgrade', 'assigned_to'), name='one_subgrade_task_per_grader'),
        ),
    ]
