# Generated by Django 6.0.7 on 2026-07-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_alter_gradingtask_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingsheet',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='grading.gradingcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingsheet',
            unique_together={('component', 'title')},
        ),
    ]
