# Generated by Django 6.0.7 on 2026-07-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_alter_gradingsheet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingcomponent',
            name='public_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
